config/routes.rb
Rails.application.routes.draw do
  get "search/index", to: "search#index", as: "search_index"
  get "search/get/:data", to: "search#get", as: "search_get"
  post "search", to: "search#search", as: "search_search"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "application#index"

  get "registration", to: "users#new"
  post "registration", to: "users#create"

  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  resources :genres
  resources :artists
  resources :albums
  resources :songs
  resources :playlists

  get "playlist_song/:song_id", to: "playlists#song_to_playlist_new", as: "playlist_song"
  post "playlist_song_add", to: "playlists#add_song_to_playlist", as: "playlist_song_add"

end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
  end

  def get
    @genres = Genre.all.where("lower(name) LIKE :data", data: "#{params[:data]}")
    @songs = Song.all.where("lower(title) LIKE :data", data: "#{params[:data]}")
    @artists = Artist.all.where("lower(name) LIKE :data", data: "#{params[:data]}")
    @albums = Album.all.where("lower(name) LIKE :data", data: "#{params[:data]}")
    @playlists = Playlist.all.where("lower(name) LIKE :data", data: "#{params[:data]}")
  end
  
  def search
    data = params[:search]
    redirect_to search_get_path(data)
  end
end

app/helpers/search_helper.rb
module SearchHelper
  def random_color
    color = "#{rand(1...255)} #{rand(1...255)} #{rand(1...255)}"
  end
end

app/views/search/get.html.erb
<div class="text-center" style="margin-top: 40px;margin-bottom: 50px;"> 
  <h1 class="mb-4 text-4xl font-extrabold tracking-tight leading-none text-gray-900 md:text-5xl lg:text-6xl dark:text-white">Search Results...</h1>
</div>
<div class="flex justify-center my-5">
  <div class="max-w-2xl mx-auto" style="width: 400px;">
    <div class="p-4 max-w-md bg-white rounded-lg border shadow-md sm:p-8 dark:bg-gray-800 dark:border-gray-700">
      <div class="flow-root">
        <ul role="list" class="divide-y divide-gray-200 dark:divide-gray-700">
          <% @genres.each do |genre| %>
            <%= link_to genre do %>
              <li class="py-3 sm:py-4 hover:bg-gray-200 rounded-lg px-2">
                <div class="flex items-center space-x-4">
                  <div class="p-4 text-indigo-600 text-center border border-transparent rounded" style="background-color: rgb(<%= random_color %>);">
                  </div>
                  <div class="flex-1 min-w-0">
                    <p class="text-xl font-medium text-gray-900 font-semibold truncate dark:text-white">
                      <%= genre.name %>
                    </p>
                    <p class="text-sm text-gray-500">genre</p>
                  </div>
                  <div class="items-center text-sm text-base text-gray-900 dark:text-white">
                    <%= genre.songs.count %>
                    <p class="text-sm text-gray-500 truncate dark:text-gray-400">
                      tracks
                    </p>
                  </div>
                </div>
              </li>
            <% end %>
          <% end %>
          <% @artists.each do |artist| %>
            <%= link_to artist do %>
              <li class="py-3 sm:py-4 hover:bg-gray-200 rounded-lg px-2">
                <div class="flex items-center space-x-4">
                  <div class="p-4 text-indigo-600 text-center border border-transparent rounded" style="background-color: rgb(<%= random_color %>);">
                  </div>
                  <div class="flex-1 min-w-0">
                    <p class="text-xl font-medium text-gray-900 font-semibold truncate dark:text-white">
                      <%= artist.name %>
                    </p>
                    <p class="text-sm text-gray-500">artist</p>
                  </div>
                  <div class="items-center text-sm text-base text-gray-900 dark:text-white">
                    <%= artist.songs.count %>
                    <p class="text-sm text-gray-500 truncate dark:text-gray-400">
                      tracks
                    </p>
                  </div>
                </div>
              </li>
            <% end %>
          <% end %>
          <% @playlists.each do |playlist| %>
            <%= link_to playlist do %>
              <li class="py-3 sm:py-4 hover:bg-gray-200 rounded-lg px-2">
                <div class="flex items-center space-x-4">
                  <div class="p-4 text-indigo-600 text-center border border-transparent rounded" style="background-color: rgb(<%= random_color %>);">
                  </div>
                  <div class="flex-1 min-w-0">
                    <p class="text-xl font-medium text-gray-900 font-semibold truncate dark:text-white">
                      <%= playlist.name %>
                    </p>
                    <p class="text-sm text-gray-500">playlist</p>
                  </div>
                  <div class="items-center text-sm text-base text-gray-900 dark:text-white">
                    <%= playlist.songs.count %>
                    <p class="text-sm text-gray-500 truncate dark:text-gray-400">
                      tracks
                    </p>
                  </div>
                </div>
              </li>
            <% end %>
          <% end %>
          <% @albums.each do |album| %>
            <%= link_to album do %>
              <li class="py-3 sm:py-4 hover:bg-gray-200 rounded-lg px-2">
                <div class="flex items-center space-x-4">
                  <div class="p-4 text-indigo-600 text-center border border-transparent rounded" style="background-color: rgb(<%= random_color %>);">
                  </div>
                  <div class="flex-1 min-w-0">
                    <p class="text-xl font-medium text-gray-900 font-semibold truncate dark:text-white">
                      <%= album.name %>
                    </p>
                    <p class="text-sm text-gray-500">album</p>
                  </div>
                  <div class="items-center text-sm text-base text-gray-900 dark:text-white">
                    <%= album.songs.count %>
                    <p class="text-sm text-gray-500 truncate dark:text-gray-400">
                      tracks
                    </p>
                  </div>
                </div>
              </li>
            <% end %>
          <% end %>
          <% @songs.each do |song| %>
            <%= link_to song do %>
              <li class="py-3 sm:py-4 hover:bg-gray-200 rounded-lg px-2">
                <div class="flex items-center space-x-4">
                  <div class="p-4 text-indigo-600 text-center border border-transparent rounded" style="background-color: rgb(<%= random_color %>);">
                  </div>
                  <div class="flex-1 min-w-0">
                    <p class="text-xl font-medium text-gray-900 font-semibold truncate dark:text-white">
                      <%= song.title %>
                    </p>
                    <p class="text-sm text-gray-500">song</p>
                  </div>
                  <div class="items-center text-sm text-base text-gray-900 dark:text-white">
                    <%= song.artist.name %>
                    <p class="text-sm text-gray-500 truncate dark:text-gray-400">
                      
                    </p>
                  </div>
                </div>
              </li>
            <% end %>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/search/index.html.erb
<div class="max-w-2xl mx-auto" style="padding-bottom: 500px;padding-top: 100px;">
  <%= form_with url: search_search_path do |f| %>
	  <div class="flex items-center">   
      <label for="voice-search" class="sr-only">Search</label>
      <div class="relative w-full">
          <div class="flex absolute inset-y-0 left-0 items-center pl-3 pointer-events-none">
              <svg class="w-5 h-5 text-gray-500 dark:text-gray-400" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z" clip-rule="evenodd"></path></svg>
          </div>
          <%= f.text_field :search, class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full pl-10 p-2.5  dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500", placeholder: "Search Songs, Artists, Genres and Albums..." %>
      </div>
      <%= f.submit "Submit", class: "inline-flex items-center py-2.5 px-3 ml-2 text-sm font-medium text-white bg-blue-700 rounded-lg border border-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800" %>
    </div>
  <% end %>
</div>