config/routes.rb
Rails.application.routes.draw do
  get "search/index", to: "search#index", as: "search_index"
  get "search/get/:data", to: "search#get", as: "search_get"
  post "search", to: "search#search", as: "search_search"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "application#index"

  get "registration", to: "users#new"
  post "registration", to: "users#create"

  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  resources :genres
  resources :artists
  resources :albums
  resources :songs
  resources :playlists

  get "playlist_song/:song_id", to: "playlists#song_to_playlist_new", as: "playlist_song"
  post "playlist_song_add", to: "playlists#add_song_to_playlist", as: "playlist_song_add"

end

app/models/song.rb
class Song < ApplicationRecord
  
  validates :title, presence: true, length: { minimum: 3 }

  belongs_to :artist
  belongs_to :genre
  belongs_to :album

  has_one_attached :audio, dependent: :delete_all

end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

  before_action :authorize, only: [:new, :create, :edit, :destroy, :update]

  def index
    @songs = Song.all()
  end

  def show
    @song = Song.find(params[:id])
  end

  def new
    @song = Song.new()
  end

  def create
    @song = Song.new(song_params)
    if @song.save
      redirect_to songs_path, notice: "Song added!"
    else
      redirect_to new_song_path, alert: "Such song already exists!"
    end
  end

  def edit
    @song = Song.find(params[:id])
  end

  def update
    @song = Song.find(params[:id])
    if @song.update(song_params)
      redirect_to @song, notice: "Song updated!"
    else
      redirect_to edit_song_path(@song), alert: "Such song cannot be changed!"
    end
  end

  def destroy
    @song = Song.find(params[:id])
    @song.destroy

    redirect_to songs_path, notice: "Song deleted!"
  end

  private
  def song_params
    artist_name = params[:song][:artist]
    album_name = params[:song][:album]
    genre_id = params[:song][:genre]
    song_audio = params[:song][:audio]

    pars = {}

    if !Artist.exists?(name: artist_name)
      Artist.create(name: artist_name, about: "To be added later...")
    end
    pars[:artist] = Artist.find_by(name: artist_name)
    if !Album.exists?(name: album_name)
      if params[:song][:single]
        album_name = "#{params[:song][:title]}-Single"
        Album.create(name: album_name, artist: pars[:artist])
      else
        Album.create(name: album_name, artist: pars[:artist])
      end
    end
    pars[:album] = Album.find_by(name: album_name)
    pars[:genre] = Genre.find(genre_id)
    pars[:title] = params[:song][:title]
    pars[:audio] = song_audio

    pars
  end

end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/songs/_form.html.erb
<div class="flex justify-center my-8">
  <div class="w-full max-w-xs">
    <div class="bg-gray-100 shadow-md rounded px-8 pt-6 pb-8 mb-4">
      <%= form_with model: song do |form| %>
      <h3 class="pt-4 text-2xl font-bold mb-8"><%= type %></h3>
        <div class="mb-4">
          <%= form.label :title, class: "block text-gray-700 text-sm font-bold" %><br>
          <%= form.text_field :title, class: "shadow appearance-none border rounded w-full px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
        </div>

        <div class="mb-4">
          <%= form.label :artist, class: "block text-gray-700 text-sm font-bold" %><br>
          <%= form.text_field :artist, class: "shadow appearance-none border rounded w-full px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
        </div>
        <div class="mb-4">
          <%= form.check_box :single %>
          <%= form.label :single, "Single" %> 
        </div>
        <div class="mb-4">
          <%= form.label :album, class: "block text-gray-700 text-sm font-bold" %><br>
          <%= form.text_field :album, class: "shadow appearance-none border rounded w-full px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
        </div>

        <div class="mb-4">
          <%= form.label :genre, class: "block text-gray-700 text-sm font-bold" %><br>
          <%= form.collection_select :genre, Genre.all, :id, :name %>
        </div>

        <div class="mb-4">
          <%= form.label :audio, class: "block text-gray-700 text-sm font-bold" %><br>
          <%= form.file_field :audio %>
        </div>
        <div class="flex items-center justify-between">
          <%= form.submit act, class: "bg-green-700 cursor-pointer hover:bg-green-600 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/songs/edit.html.erb
<div class="flex justify-center my-8">
  <div class="w-full max-w-xs">
    <div class="bg-gray-100 shadow-md rounded px-8 pt-6 pb-8 mb-4">
      <%= form_with model: @song do |form| %>
      <h3 class="pt-4 text-2xl font-bold mb-8">Edit song</h3>
        <div class="mb-4">
          <%= form.label :title, class: "block text-gray-700 text-sm font-bold" %><br>
          <%= form.text_field :title, class: "shadow appearance-none border rounded w-full px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
        </div>

        <div class="mb-4">
          <%= form.label :artist, class: "block text-gray-700 text-sm font-bold" %><br>
          <%= form.text_field :artist, class: "shadow appearance-none border rounded w-full px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline", value: @song.artist.name %>
        </div>
        <div class="mb-4">
          <%= form.check_box :single %>
          <%= form.label :single, "Single" %> 
        </div>
        <div class="mb-4">
          <%= form.label :album, class: "block text-gray-700 text-sm font-bold" %><br>
          <%= form.text_field :album, class: "shadow appearance-none border rounded w-full px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline", value: @song.album.name %>
        </div>

        <div class="mb-4">
          <%= form.label :genre, class: "block text-gray-700 text-sm font-bold" %><br>
          <%= form.collection_select :genre, Genre.all, :id, :name %>
        </div>

        <div class="mb-4">
          <%= form.label :audio, class: "block text-gray-700 text-sm font-bold" %><br>
          <%= form.file_field :audio %>
        </div>
        <div class="flex items-center justify-between">
          <%= form.submit "Update", class: "bg-green-700 cursor-pointer hover:bg-green-600 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/songs/index.html.erb
<div class="min-h-screen bg-gray-100 flex flex-col items-center justify-center">

  <div class="flex flex-col text-center mb-10">
    <h1 class="text-4xl font-extrabold tracking-tight leading-none text-gray-900 md:text-5xl lg:text-6xl ">Trending <span class="text-orange-700">Songs</span>.</h1>
    <% if logged_in? %>
      <% if is_admin? %>
        <div class="text-center pt-4">
          <%= link_to "Add new", new_song_path, class: "text-sm font-medium text-indigo-800 hover:text-indigo-500 hover:underline" %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="max-w-xl bg-white rounded-lg shadow-lg overflow-hidden">
    <div class="relative">
        <%= image_tag "wood.jpg", class: "object-cover" %>
      <div class="absolute p-4 inset-0 flex flex-col justify-end bg-gradient-to-b from-transparent to-gray-900 backdrop backdrop-blur-5 text-white">
        <h3 class="font-bold">Pashanim - BMW</h3>
        <span class="opacity-70">Himmel ueber Berlin</span>
      </div>
    </div>
    <div>
      <div class="relative h-1 bg-gray-200">
        <div class="absolute h-full w-1/2 bg-green-500 flex items-center justify-end">
          <div class="rounded-full w-3 h-3 bg-white shadow"></div>
        </div>
      </div>
    </div>
    <div class="flex justify-between text-xs font-semibold text-gray-500 px-4 py-2">
      <div>
        1:50
      </div>
      <div class="flex space-x-3 p-2">
        <button class="focus:outline-none">
          <svg class="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polygon points="19 20 9 12 19 4 19 20"></polygon><line x1="5" y1="19" x2="5" y2="5"></line></svg>
        </button>
        <button class="rounded-full w-8 h-8 flex items-center justify-center pl-0.5 ring-2 ring-gray-100 focus:outline-none">
          <svg class="w-5 h-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polygon points="5 3 19 12 5 21 5 3"></polygon></svg>
        </button>
        <button class="focus:outline-none">
          <svg class="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polygon points="5 4 15 12 5 20 5 4"></polygon><line x1="19" y1="5" x2="19" y2="19"></line></svg>
        </button>
      </div>
      <div>
        3:00
      </div>
    </div>

    <ul class="text-xs sm:text-base divide-y border-t cursor-default">
      <li class="flex items-center space-x-3 hover:bg-gray-100">
        <button class="p-3 hover:bg-green-500 group focus:outline-none">
          <svg class="w-4 h-4 group-hover:text-white" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polygon points="5 3 19 12 5 21 5 3"></polygon></svg>
        </button>
        <div class="flex-1">
          Lil Uzi Vert - Longer
        </div>
        <div class="text-xs text-gray-400 p-2">
          5:58
        </div>
      </li>
      <li class="flex items-center space-x-3 hover:bg-gray-100">
        <button class="p-3 hover:bg-green-500 group focus:outline-none">
          <svg class="w-4 h-4 group-hover:text-white" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polygon points="5 3 19 12 5 21 5 3"></polygon></svg>
        </button>
        <div class="flex-1">
          OBOY - FAST FAST
        </div>
        <div class="text-xs text-gray-400 p-2">
          2:58
        </div>
      </li>
    </ul>

  </div>
</div>

app/views/songs/new.html.erb
<%= render "form", song: @song, type: "Add song", act: "Create" %>

app/views/songs/show.html.erb
<div class="flex flex-wrap justify-center my-8">
  <div class="relative block rounded-xl border border-gray-100 p-8 shadow-xl">
    <div class="mt-4 text-gray-500 sm:pr-8">
      <h3 class="mt-4 text-xl font-bold text-gray-900"><%= @song.title %></h3>
      <%= link_to @song.artist.name, artist_path(@song.artist), class: "mt-2 text-md block hover:underline" %>
      <%= link_to @song.album.name, album_path(@song.album), class: "mt-2 text-sm block hover:underline" %>
      <audio controls class="w-full mt-5">
        <source src="<%= rails_blob_url(@song.audio) %>" type="audio/mpeg">
      </audio> 
      <div class="flex flex-row justify-end space-x-2 mt-2">
        <% if logged_in? && is_admin? %>
          <%= link_to edit_song_path(@song) do %>
            <svg class="h-10 w-10 fill-white bg-indigo-800 hover:bg-indigo-500 rounded-lg p-0.5" viewBox="0 0 20 20">
              <path d="M12.319,5.792L8.836,2.328C8.589,2.08,8.269,2.295,8.269,2.573v1.534C8.115,4.091,7.937,4.084,7.783,4.084c-2.592,0-4.7,2.097-4.7,4.676c0,1.749,0.968,3.337,2.528,4.146c0.352,0.194,0.651-0.257,0.424-0.529c-0.415-0.492-0.643-1.118-0.643-1.762c0-1.514,1.261-2.747,2.787-2.747c0.029,0,0.06,0,0.09,0.002v1.632c0,0.335,0.378,0.435,0.568,0.245l3.483-3.464C12.455,6.147,12.455,5.928,12.319,5.792 M8.938,8.67V7.554c0-0.411-0.528-0.377-0.781-0.377c-1.906,0-3.457,1.542-3.457,3.438c0,0.271,0.033,0.542,0.097,0.805C4.149,10.7,3.775,9.762,3.775,8.76c0-2.197,1.798-3.985,4.008-3.985c0.251,0,0.501,0.023,0.744,0.069c0.212,0.039,0.412-0.124,0.412-0.34v-1.1l2.646,2.633L8.938,8.67z M14.389,7.107c-0.34-0.18-0.662,0.244-0.424,0.529c0.416,0.493,0.644,1.118,0.644,1.762c0,1.515-1.272,2.747-2.798,2.747c-0.029,0-0.061,0-0.089-0.002v-1.631c0-0.354-0.382-0.419-0.558-0.246l-3.482,3.465c-0.136,0.136-0.136,0.355,0,0.49l3.482,3.465c0.189,0.186,0.568,0.096,0.568-0.245v-1.533c0.153,0.016,0.331,0.022,0.484,0.022c2.592,0,4.7-2.098,4.7-4.677C16.917,9.506,15.948,7.917,14.389,7.107 M12.217,15.238c-0.251,0-0.501-0.022-0.743-0.069c-0.212-0.039-0.411,0.125-0.411,0.341v1.101l-2.646-2.634l2.646-2.633v1.116c0,0.174,0.126,0.318,0.295,0.343c0.158,0.024,0.318,0.034,0.486,0.034c1.905,0,3.456-1.542,3.456-3.438c0-0.271-0.032-0.541-0.097-0.804c0.648,0.719,1.022,1.659,1.022,2.66C16.226,13.451,14.428,15.238,12.217,15.238"></path>        
            </svg>
          <% end %>
          <%= link_to song_path(@song), data: {
            turbo_method: :delete,
            turbo_confirm: "Are you sure?"
          } do %>
            <svg class="h-10 w-10 fill-white bg-red-800 hover:bg-red-500 rounded-lg p-0.5" viewBox="0 0 20 20">
              <path d="M17.114,3.923h-4.589V2.427c0-0.252-0.207-0.459-0.46-0.459H7.935c-0.252,0-0.459,0.207-0.459,0.459v1.496h-4.59c-0.252,0-0.459,0.205-0.459,0.459c0,0.252,0.207,0.459,0.459,0.459h1.51v12.732c0,0.252,0.207,0.459,0.459,0.459h10.29c0.254,0,0.459-0.207,0.459-0.459V4.841h1.511c0.252,0,0.459-0.207,0.459-0.459C17.573,4.127,17.366,3.923,17.114,3.923M8.394,2.886h3.214v0.918H8.394V2.886z M14.686,17.114H5.314V4.841h9.372V17.114z M12.525,7.306v7.344c0,0.252-0.207,0.459-0.46,0.459s-0.458-0.207-0.458-0.459V7.306c0-0.254,0.205-0.459,0.458-0.459S12.525,7.051,12.525,7.306M8.394,7.306v7.344c0,0.252-0.207,0.459-0.459,0.459s-0.459-0.207-0.459-0.459V7.306c0-0.254,0.207-0.459,0.459-0.459S8.394,7.051,8.394,7.306"></path>        
            </svg>
          <% end %>
        <% end %>
        <% if logged_in? %>
          <%= link_to playlist_song_path(@song) do %>
            <svg class="h-10 w-10 fill-white bg-green-800 hover:bg-green-500 rounded-lg p-0.5" viewBox="0 0 20 20">
              <path d="M17.592,8.936l-6.531-6.534c-0.593-0.631-0.751-0.245-0.751,0.056l0.002,2.999L5.427,9.075H2.491c-0.839,0-0.162,0.901-0.311,0.752l3.683,3.678l-3.081,3.108c-0.17,0.171-0.17,0.449,0,0.62c0.169,0.17,0.448,0.17,0.618,0l3.098-3.093l3.675,3.685c-0.099-0.099,0.773,0.474,0.773-0.296v-2.965l3.601-4.872l2.734-0.005C17.73,9.688,18.326,9.669,17.592,8.936 M3.534,9.904h1.906l4.659,4.66v1.906L3.534,9.904z M10.522,13.717L6.287,9.48l4.325-3.124l3.088,3.124L10.522,13.717z M14.335,8.845l-3.177-3.177V3.762l5.083,5.083H14.335z"></path>            </svg>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>