config/routes.rb
Rails.application.routes.draw do
  get "search/index", to: "search#index", as: "search_index"
  get "search/get/:data", to: "search#get", as: "search_get"
  post "search", to: "search#search", as: "search_search"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "application#index"

  get "registration", to: "users#new"
  post "registration", to: "users#create"

  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  resources :genres
  resources :artists
  resources :albums
  resources :songs
  resources :playlists

  get "playlist_song/:song_id", to: "playlists#song_to_playlist_new", as: "playlist_song"
  post "playlist_song_add", to: "playlists#add_song_to_playlist", as: "playlist_song_add"

end

app/models/playlist.rb
class Playlist < ApplicationRecord
  belongs_to :user
  has_many :playlist_songs, dependent: :delete_all

  has_many :songs, through: :playlist_songs
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController

  before_action :authorize, only: [:new, :create, :edit, :destroy, :update]
  
  def index
    @playlists = Playlist.first(20)
  end

  def show
    @playlist = Playlist.find(params[:id])
  end

  def new
    @playlist = Playlist.new()
  end

  def create
    @playlist = Playlist.new(name: params[:playlist][:name], user: current_user)
    if @playlist.save
      redirect_to playlists_path, notice: "Playlist added!"
    else
      redirect_to new_playlist_path, arlert: "Playlist already exists!"
    end
  end

  def edit
    @playlist = Playlist.find(params[:id])
  end

  def update
    @playlist = Playlist.find(params[:id])
    if @playlist.update(name: params[:playlist][:name], user: current_user)
      redirect_to @playlist, notice: "Playlist updated!"
    else
      redirect_to edit_playlist_path, arlert: "Please enter different playlist name."
    end
  end

  def destroy
    @playlist = Playlist.find(params[:id])
    @playlist.destroy

    redirect_to playlists_path, notice: "Playlists deleted!"
  end

  def song_to_playlist_new
    @song = Song.find(params[:song_id])
  end

  def add_song_to_playlist
    song_id = params[:song]
    playlist_id = params[:playlist]
    song = Song.find(song_id)
    playlist = Playlist.find(playlist_id)
    temp = PlaylistSong.new(playlist: playlist, song: song)
    if temp.save
      redirect_to playlists_path, notice: "Successfuly added song to playlist!"
    else
      redirect_to playlist_song_path(song), alert: "Failed!"
    end
  end

end

app/helpers/playlists_helper.rb
module PlaylistsHelper
  def random_color
    color = "#{rand(1...255)} #{rand(1...255)} #{rand(1...255)}"
  end
end

app/views/playlists/edit.html.erb
<div class="flex justify-center my-8">
  <div class="w-full max-w-xs">
    <div class="bg-gray-100 shadow-md rounded px-8 pt-6 pb-8 mb-4">
      <%= form_with model: @playlist do |form| %>
      <h3 class="pt-4 text-2xl font-bold mb-8">Update playlist</h3>
        <div class="mb-4">
          <%= form.label :name, class: "block text-gray-700 text-sm font-bold" %><br>
          <%= form.text_field :name, class: "shadow appearance-none border rounded w-full px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
        </div>
        <div class="flex items-center justify-between">
          <%= form.submit "Update", class: "bg-green-700 cursor-pointer hover:bg-green-600 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/playlists/index.html.erb
<div class="text-center" style="margin-top: 80px;"> 
  <h1 class="mb-4 text-4xl font-extrabold tracking-tight leading-none text-gray-900 md:text-5xl lg:text-6xl dark:text-white">Trending <span class="text-blue-600 dark:text-blue-500">Playlists</span>.</h1>
  <div class="flex justify-center items-center mb-4">
    <% if logged_in? %>
      <% if true %>
        <%= link_to "Add new", new_playlist_path, class: "text-sm font-medium text-blue-600 hover:underline dark:text-blue-500" %>
      <% else %>
        <p class="text-sm font-medium text-grey-600 dark:text-blue-500">Add new</p>
      <% end %>
    <% end %>
  </div>
</div>
<div class="flex justify-center my-5">
  <div class="max-w-2xl mx-auto" style="width: 400px;">
    <div class="p-4 max-w-md bg-white rounded-lg border shadow-md sm:p-8 dark:bg-gray-800 dark:border-gray-700">
      <div class="flow-root">
        <ul role="list" class="divide-y divide-gray-200 dark:divide-gray-700">
          <% @playlists.each do |playlist| %>
          <%= link_to playlist do %>
              <li class="py-3 sm:py-4 hover:bg-gray-200 rounded-lg px-2">
                <div class="flex items-center space-x-4">
                  <div class="p-4 text-indigo-600 text-center border border-transparent rounded" style="background-color: rgb(<%= random_color %>);">
                  </div>
                  <div class="flex-1 min-w-0">
                    <p class="text-xl font-medium text-gray-900 font-semibold truncate dark:text-white">
                      <%= playlist.name %>
                    </p>
                  </div>
                  <div class="items-center text-sm text-base text-gray-900 dark:text-white">
                    <%= playlist.songs.count %>
                    <p class="text-sm text-gray-500 truncate dark:text-gray-400">
                      tracks
                    </p>
                  </div>
                </div>
              </li>
            <% end %>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/playlists/new.html.erb
<div class="flex justify-center my-8">
  <div class="w-full max-w-xs">
    <div class="bg-gray-100 shadow-md rounded px-8 pt-6 pb-8 mb-4">
      <%= form_with model: @playlist do |form| %>
      <h3 class="pt-4 text-2xl font-bold mb-8">Create new playlist</h3>
        <div class="mb-4">
          <%= form.label :name, class: "block text-gray-700 text-sm font-bold" %><br>
          <%= form.text_field :name, class: "shadow appearance-none border rounded w-full px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
        </div>
        <div class="flex items-center justify-between">
          <%= form.submit "Create", class: "bg-green-700 cursor-pointer hover:bg-green-600 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/playlists/show.html.erb
<div class="flex flex-wrap justify-center my-8">
  <div class="relative block rounded-xl border border-gray-100 p-8 shadow-xl" style="width:400px;">
    <div class="mt-4 text-gray-500 sm:pr-8">
      <h3 class="mt-4 text-xl font-bold text-gray-900"><%= @playlist.name %></h3>
      <div class="flex flex-row justify-end space-x-2 mt-2">
        <% if logged_in? && is_admin? %>
          <%= link_to edit_playlist_path(@playlist) do %>
            <svg class="h-10 w-10 fill-white bg-indigo-800 hover:bg-indigo-500 rounded-lg p-0.5" viewBox="0 0 20 20">
              <path d="M12.319,5.792L8.836,2.328C8.589,2.08,8.269,2.295,8.269,2.573v1.534C8.115,4.091,7.937,4.084,7.783,4.084c-2.592,0-4.7,2.097-4.7,4.676c0,1.749,0.968,3.337,2.528,4.146c0.352,0.194,0.651-0.257,0.424-0.529c-0.415-0.492-0.643-1.118-0.643-1.762c0-1.514,1.261-2.747,2.787-2.747c0.029,0,0.06,0,0.09,0.002v1.632c0,0.335,0.378,0.435,0.568,0.245l3.483-3.464C12.455,6.147,12.455,5.928,12.319,5.792 M8.938,8.67V7.554c0-0.411-0.528-0.377-0.781-0.377c-1.906,0-3.457,1.542-3.457,3.438c0,0.271,0.033,0.542,0.097,0.805C4.149,10.7,3.775,9.762,3.775,8.76c0-2.197,1.798-3.985,4.008-3.985c0.251,0,0.501,0.023,0.744,0.069c0.212,0.039,0.412-0.124,0.412-0.34v-1.1l2.646,2.633L8.938,8.67z M14.389,7.107c-0.34-0.18-0.662,0.244-0.424,0.529c0.416,0.493,0.644,1.118,0.644,1.762c0,1.515-1.272,2.747-2.798,2.747c-0.029,0-0.061,0-0.089-0.002v-1.631c0-0.354-0.382-0.419-0.558-0.246l-3.482,3.465c-0.136,0.136-0.136,0.355,0,0.49l3.482,3.465c0.189,0.186,0.568,0.096,0.568-0.245v-1.533c0.153,0.016,0.331,0.022,0.484,0.022c2.592,0,4.7-2.098,4.7-4.677C16.917,9.506,15.948,7.917,14.389,7.107 M12.217,15.238c-0.251,0-0.501-0.022-0.743-0.069c-0.212-0.039-0.411,0.125-0.411,0.341v1.101l-2.646-2.634l2.646-2.633v1.116c0,0.174,0.126,0.318,0.295,0.343c0.158,0.024,0.318,0.034,0.486,0.034c1.905,0,3.456-1.542,3.456-3.438c0-0.271-0.032-0.541-0.097-0.804c0.648,0.719,1.022,1.659,1.022,2.66C16.226,13.451,14.428,15.238,12.217,15.238"></path>        
            </svg>
          <% end %>
          <%= link_to playlist_path(@playlist), data: {
            turbo_method: :delete,
            turbo_confirm: "Are you sure?"
          } do %>
            <svg class="h-10 w-10 fill-white bg-red-800 hover:bg-red-500 rounded-lg p-0.5" viewBox="0 0 20 20">
              <path d="M17.114,3.923h-4.589V2.427c0-0.252-0.207-0.459-0.46-0.459H7.935c-0.252,0-0.459,0.207-0.459,0.459v1.496h-4.59c-0.252,0-0.459,0.205-0.459,0.459c0,0.252,0.207,0.459,0.459,0.459h1.51v12.732c0,0.252,0.207,0.459,0.459,0.459h10.29c0.254,0,0.459-0.207,0.459-0.459V4.841h1.511c0.252,0,0.459-0.207,0.459-0.459C17.573,4.127,17.366,3.923,17.114,3.923M8.394,2.886h3.214v0.918H8.394V2.886z M14.686,17.114H5.314V4.841h9.372V17.114z M12.525,7.306v7.344c0,0.252-0.207,0.459-0.46,0.459s-0.458-0.207-0.458-0.459V7.306c0-0.254,0.205-0.459,0.458-0.459S12.525,7.051,12.525,7.306M8.394,7.306v7.344c0,0.252-0.207,0.459-0.459,0.459s-0.459-0.207-0.459-0.459V7.306c0-0.254,0.207-0.459,0.459-0.459S8.394,7.051,8.394,7.306"></path>        
            </svg>
          <% end %>
        <% end %>
      </div>
    </div>
    <div class="flex flex-col mt-5">
      <ul>
        <% @playlist.songs.each do |song| %>
          <%= link_to song do %>
            <li class="text-center hover:bg-gray-300">
              <p class="text-m"><%= "#{song.artist.name} - #{song.title}" %></p>
              <audio controls class="w-full">
                <source src="<%= rails_blob_url(song.audio) %>" type="audio/mpeg">
              </audio>
            </li>
          <% end %>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/playlists/song_to_playlist_new.erb
<div class="flex justify-center my-8">
  <div class="w-full max-w-xs">
    <div class="bg-gray-100 shadow-md rounded px-8 pt-6 pb-8 mb-4">
      <%= form_with url: playlist_song_add_path do |form| %>
        <h3 class="pt-4 text-2xl font-bold mb-8">Add to playlist</h3>
        <div class="mb-4">
          <%= form.label :playlist, class: "block text-gray-700 text-sm font-bold" %><br>
          <%= form.collection_select :playlist, Playlist.all, :id, :name %>
        </div>
        <div class="mb-4 hidden">
          <%= form.label :song, class: "block text-gray-700 text-sm font-bold" %><br>
          <%= form.text_field :song, class: "shadow appearance-none border rounded w-full px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline", value: @song.id %>
        </div>
        <div class="flex items-center justify-between">
          <%= form.submit "Add", class: "bg-green-700 cursor-pointer hover:bg-green-600 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
        </div>
      <% end %>
    </div>
  </div>
</div>