config/routes.rb
Rails.application.routes.draw do
  get "search/index", to: "search#index", as: "search_index"
  get "search/get/:data", to: "search#get", as: "search_get"
  post "search", to: "search#search", as: "search_search"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "application#index"

  get "registration", to: "users#new"
  post "registration", to: "users#create"

  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  resources :genres
  resources :artists
  resources :albums
  resources :songs
  resources :playlists

  get "playlist_song/:song_id", to: "playlists#song_to_playlist_new", as: "playlist_song"
  post "playlist_song_add", to: "playlists#add_song_to_playlist", as: "playlist_song_add"

end

app/models/album.rb
class Album < ApplicationRecord
  belongs_to :artist
  has_many :songs, dependent: :delete_all
  has_one_attached :cover, dependent: :delete_all

  validates :name, uniqueness: true, presence: true, length: { minimum: 3 }
  validates :release_date, presence: true, length: { maximum: 4 }

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class

  
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_one_attached :avatar, dependent: :delete_all
  
  has_many :albums, dependent: :delete_all
  has_many :songs, dependent: :delete_all

  validates :name, uniqueness: true, presence: true, length: { minimum: 3 }
  validates :about, presence: true, length: { minimum: 15 }

end

app/models/genre.rb
class Genre < ApplicationRecord

  validates :name, uniqueness: true, presence: true, length: { minimum: 3 }

  has_many :songs, dependent: :delete_all

end

app/models/playlist.rb
class Playlist < ApplicationRecord
  belongs_to :user
  has_many :playlist_songs, dependent: :delete_all

  has_many :songs, through: :playlist_songs
end

app/models/playlist_song.rb
class PlaylistSong < ApplicationRecord
  belongs_to :playlist
  belongs_to :song
end

app/models/song.rb
class Song < ApplicationRecord
  
  validates :title, presence: true, length: { minimum: 3 }

  belongs_to :artist
  belongs_to :genre
  belongs_to :album

  has_one_attached :audio, dependent: :delete_all

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :playlists
  
  validates :username, uniqueness: true, presence: true, length: { minimum: 5 }
  validates :password, presence: true, length: { minimum: 5 }
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :authorize, only: [:new, :create, :edit, :destroy, :update]
  
  def index
    @albums = Album.first(20)
  end

  def show
    @album = Album.find(params[:id])
  end

  def new
    @album = Album.new()
  end

  def create
    @album = Album.new(album_params)
    if @album.save
      redirect_to albums_path, notice: "Song added!"
    else
      redirect_to new_album_path, alert: "Such album already exists!"
    end
  end

  def edit
    @album = Album.find(params[:id])
  end

  def update
    @album = Album.find(params[:id])

    album_name = params[:album][:name]
    release_date = params[:album][:release_date]
    album_cover = params[:album][:cover]
    artist = @album.artist
    if params[:album][:cover] == nil
      album_cover = @album.cover[0]
    end
    if @album.update(name: album_name, artist: artist, release_date: release_date, cover: album_cover)
      redirect_to @album, notice: "Genre updated!"
    else
      redirect_to edit_album_path(@genre), alert: "Such album already exists!"
    end
  end

  def destroy
    @album = Album.find(params[:id])
    @album.destroy

    redirect_to albums_path, notice: "Album deleted!"
  end

  private
  def album_params
    pars = {}
    
    album_name = params[:album][:name]
    release_date = params[:album][:release_date]
    artist_name = params[:album][:artist]
    album_cover = params[:album][:cover]

    if !Artist.exists?(name: artist_name)
      Artist.create(name: artist_name, about: "To be added later...")
    end
    
    pars[:artist] = Artist.find_by(name: artist_name)
    pars[:name] = album_name
    pars[:release_date] = release_date
    pars[:cover] = album_cover

    pars
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

  before_action :authorize, only: [:new, :create, :edit, :destroy, :update]

  def index
    @songs = Song.all()
  end

  def show
    @song = Song.find(params[:id])
  end

  def new
    @song = Song.new()
  end

  def create
    @song = Song.new(song_params)
    if @song.save
      redirect_to songs_path, notice: "Song added!"
    else
      redirect_to new_song_path, alert: "Such song already exists!"
    end
  end

  def edit
    @song = Song.find(params[:id])
  end

  def update
    @song = Song.find(params[:id])
    if @song.update(song_params)
      redirect_to @song, notice: "Song updated!"
    else
      redirect_to edit_song_path(@song), alert: "Such song cannot be changed!"
    end
  end

  def destroy
    @song = Song.find(params[:id])
    @song.destroy

    redirect_to songs_path, notice: "Song deleted!"
  end

  private
  def song_params
    artist_name = params[:song][:artist]
    album_name = params[:song][:album]
    genre_id = params[:song][:genre]
    song_audio = params[:song][:audio]

    pars = {}

    if !Artist.exists?(name: artist_name)
      Artist.create(name: artist_name, about: "To be added later...")
    end
    pars[:artist] = Artist.find_by(name: artist_name)
    if !Album.exists?(name: album_name)
      if params[:song][:single]
        album_name = "#{params[:song][:title]}-Single"
        Album.create(name: album_name, artist: pars[:artist])
      else
        Album.create(name: album_name, artist: pars[:artist])
      end
    end
    pars[:album] = Album.find_by(name: album_name)
    pars[:genre] = Genre.find(genre_id)
    pars[:title] = params[:song][:title]
    pars[:audio] = song_audio

    pars
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new()
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: "Thank you for registration!"
    else
      redirect_to registration_path, alert: "Username is already taken!"
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end

end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
  def random_color
    color = "#{rand(1...255)} #{rand(1...255)} #{rand(1...255)}"
  end
end

app/helpers/genres_helper.rb
module GenresHelper
  def random_color
    color = "#{rand(1...255)} #{rand(1...255)} #{rand(1...255)}"
  end
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
  def random_color
    color = "#{rand(1...255)} #{rand(1...255)} #{rand(1...255)}"
  end
end

app/helpers/search_helper.rb
module SearchHelper
  def random_color
    color = "#{rand(1...255)} #{rand(1...255)} #{rand(1...255)}"
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer aria-label="Site Footer" class="bg-gray-200">
  <div
    class="relative mx-auto max-w-screen-xl px-4 py-16 sm:px-6 lg:px-8 lg:pt-24"
  >
    <div class="lg:flex lg:items-end lg:justify-between">
      <div>
        <div class="flex justify-center lg:justify-start">
          <%= link_to "chanson", root_path, class: "font-extrabold text-3xl text-indigo-600 hover:text-indigo-800" %>
        </div>

        <p
          class="mx-auto mt-6 max-w-md text-center leading-relaxed text-gray-500 lg:text-left"
        >
        chanceon is an online audio distribution platform and music sharing website that enables its users to upload, play and download songs. 
        </p>
      </div>

      <nav aria-label="Footer Nav" class="mt-12 lg:mt-0">
        <ul
          class="flex flex-wrap justify-center gap-6 md:gap-8 lg:justify-end lg:gap-12"
        >
          <li>
            <a class="text-gray-700 transition hover:text-gray-700/75" href="/">
              About
            </a>
          </li>

          <li>
            <a class="text-gray-700 transition hover:text-gray-700/75" href="/">
              Discover
            </a>
          </li>

          <li>
            <a class="text-gray-700 transition hover:text-gray-700/75" href="/">
              Github
            </a>
          </li>
        </ul>
      </nav>
    </div>

    <p class="mt-12 text-center text-sm text-gray-500 lg:text-right">
      Copyright &copy; 2022. Developed for educational purposes.
    </p>
  </div>
</footer>

app/views/layouts/_header.html.erb
<div class="header-2">
  <nav class="bg-white py-2 md:py-4 ">
    <div class="container px-4 mx-auto md:flex md:items-center">
      <div class="flex justify-between items-center">
        <%= link_to "chanson", root_path, class: "font-bold text-xl text-indigo-600" %>
        <button class="border border-solid border-gray-600 px-3 py-1 rounded text-gray-600 opacity-50 hover:opacity-75 md:hidden" id="navbar-toggle">
          📖
        </button>
      </div>

      <div class="hidden md:flex flex-col md:flex-row md:ml-auto mt-3 md:mt-0" id="navbar-collapse">
        <%= link_to "Search", search_index_path, class: "p-2 lg:px-4 md:mx-2 text-gray-600 rounded hover:bg-gray-200 hover:text-gray-700 transition-colors duration-300" %>
        <%= link_to "Playlists", playlists_path, class: "p-2 lg:px-4 md:mx-2 text-gray-600 rounded hover:bg-gray-200 hover:text-gray-700 transition-colors duration-300" %>
        <%= link_to "Artists", artists_path, class: "p-2 lg:px-4 md:mx-2 text-gray-600 rounded hover:bg-gray-200 hover:text-gray-700 transition-colors duration-300" %>
        <%= link_to "Albums", albums_path, class: "p-2 lg:px-4 md:mx-2 text-gray-600 rounded hover:bg-gray-200 hover:text-gray-700 transition-colors duration-300" %>
        <%= link_to "Songs", songs_path, class: "p-2 lg:px-4 md:mx-2 text-gray-600 rounded hover:bg-gray-200 hover:text-gray-700 transition-colors duration-300" %>
        <%= link_to "Genres", genres_path, class: "p-2 lg:px-4 md:mx-2 text-gray-600 rounded hover:bg-gray-200 hover:text-gray-700 transition-colors duration-300" %>
        <% if logged_in? %>
          <%= button_to "Logout", logout_path, method: "delete", class: "p-2 lg:px-4 md:mx-2 text-red-600 text-center border border-solid border-red-600 rounded hover:bg-red-600 hover:text-white transition-colors duration-300 mt-1 md:mt-0 md:ml-1" %>
        <% else %>
          <%= link_to "Login", login_path, class: "p-2 lg:px-4 md:mx-2 text-indigo-600 text-center border border-transparent rounded hover:bg-indigo-100 hover:text-indigo-700 transition-colors duration-300" %>
          <%= link_to "Register", registration_path, class: "p-2 lg:px-4 md:mx-2 text-indigo-600 text-center border border-solid border-indigo-600 rounded hover:bg-indigo-600 hover:text-white transition-colors duration-300 mt-1 md:mt-0 md:ml-1" %>
        <% end %>
      </div>
    </div>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>chanson</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "/layouts/header" %>
    
    <% if flash[:notice] %>
      <div class="bg-green-100 rounded-lg py-5 px-6 mb-3 text-base text-green-700 inline-flex items-center w-full" role="alert">
        <svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="check-circle" class="w-4 h-4 mr-2 fill-current" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
          <path fill="currentColor" d="M504 256c0 136.967-111.033 248-248 248S8 392.967 8 256 119.033 8 256 8s248 111.033 248 248zM227.314 387.314l184-184c6.248-6.248 6.248-16.379 0-22.627l-22.627-22.627c-6.248-6.249-16.379-6.249-22.628 0L216 308.118l-70.059-70.059c-6.248-6.248-16.379-6.248-22.628 0l-22.627 22.627c-6.248 6.248-6.248 16.379 0 22.627l104 104c6.249 6.249 16.379 6.249 22.628.001z"></path>
        </svg>
        <%= flash[:notice] %>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="bg-red-100 rounded-lg py-5 px-6 mb-3 text-base text-red-700 inline-flex items-center w-full" role="alert">
        <svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="times-circle" class="w-4 h-4 mr-2 fill-current" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
          <path fill="currentColor" d="M256 8C119 8 8 119 8 256s111 248 248 248 248-111 248-248S393 8 256 8zm121.6 313.1c4.7 4.7 4.7 12.3 0 17L338 377.6c-4.7 4.7-12.3 4.7-17 0L256 312l-65.1 65.6c-4.7 4.7-12.3 4.7-17 0L134.4 338c-4.7-4.7-4.7-12.3 0-17l65.6-65-65.6-65.1c-4.7-4.7-4.7-12.3 0-17l39.6-39.6c4.7-4.7 12.3-4.7 17 0l65 65.7 65.1-65.6c4.7-4.7 12.3-4.7 17 0l39.6 39.6c4.7 4.7 4.7 12.3 0 17L312 256l65.6 65.1z"></path>
        </svg>
        <%= flash[:alert] %>
      </div>
    <% end %>

    <%= yield %>
    <%= render "/layouts/footer" %>
  </body>
  <script>
    var toggleBtn = document.querySelector("#navbar-toggle");
    var collapse = document.querySelector("#navbar-collapse");
    toggleBtn.onclick = () => {
      collapse.classList.toggle("hidden");
      collapse.classList.toggle("flex");
    };
  </script>
  <% if false %>
    <% console %>
  <% end %>
</html>